import { defineConfig } from 'cz-git'

export default defineConfig({
    extends: ['@commitlint/config-conventional'],
    prompt: {
        alias: { fd: 'docs: fix typos' },
        messages: {
            type: '选择你要提交的类型 :',
            scope: '选择一个提交范围（可选）:',
            customScope: '请输入自定义的提交范围 :',
            subject: '填写简短精炼的变更描述 :\n',
            body: '填写更加详细的变更描述（可选）。使用 "|" 换行 :\n',
            breaking: '列举非兼容性重大的变更（可选）。使用 "|" 换行 :\n',
            footerPrefixesSelect: '选择关联issue前缀（可选）:',
            customFooterPrefix: '输入自定义issue前缀 :',
            footer: '列举关联issue (可选) 例如: #31, #I3244 :\n',
            generatingByAI: '正在通过 AI 生成你的提交简短描述...',
            generatedSelectByAI: '选择一个 AI 生成的简短描述:',
            confirmCommit: '是否提交或修改commit ?',
        },
        types: [
            {
                value: 'feat',
                name: '✨ 特性 | feat:     新增功能',
                emoji: ':sparkles:',
            },
            {
                value: 'fix',
                name: '🐛 修复 | fix:      修复缺陷',
                emoji: ':bug:',
            },
            {
                value: 'docs',
                name: '📝 文档 | docs:     文档变更',
                emoji: ':memo:',
            },
            {
                value: 'style',
                name: '💄 样式 | style:    代码样式变更',
                emoji: ':lipstick:',
            },
            {
                value: 'refactor',
                name: '♻️  重构 | refactor: 代码重构',
                emoji: ':recycle:',
            },
            {
                value: 'perf',
                name: '⚡ 性能 | perf:     性能优化',
                emoji: ':zap:',
            },
            {
                value: 'test',
                name: '✅ 测试 | test:     添加或修改测试',
                emoji: ':white_check_mark:',
            },
            {
                value: 'build',
                name: '📦 构建 | build:    构建系统或依赖变更',
                emoji: ':package:',
            },
            {
                value: 'ci',
                name: '🎡 CI   | ci:       持续集成配置',
                emoji: ':ferris_wheel:',
            },
            {
                value: 'revert',
                name: '⏪ 回退 | revert:   回退提交',
                emoji: ':rewind:',
            },
            {
                value: 'chore',
                name: '🔨 杂项 | chore:    其他改动',
                emoji: ':hammer:',
            },
        ],
        useEmoji: true,
        emojiAlign: 'center',
        useAI: false,
        aiNumber: 1,
        themeColorCode: '',
        scopes: [],
        allowCustomScopes: true,
        allowEmptyScopes: true,
        customScopesAlign: 'bottom',
        customScopesAlias: 'custom',
        emptyScopesAlias: 'empty',
        upperCaseSubject: null,
        markBreakingChangeMode: false,
        allowBreakingChanges: ['feat', 'fix'],
        breaklineNumber: 100,
        breaklineChar: '|',
        skipQuestions: [],
        issuePrefixes: [{ value: 'closed', name: 'closed:   ISSUES has been processed' }],
        customIssuePrefixAlign: 'top',
        emptyIssuePrefixAlias: 'skip',
        customIssuePrefixAlias: 'custom',
        allowCustomIssuePrefix: true,
        allowEmptyIssuePrefix: true,
        confirmColorize: true,
        scopeOverrides: undefined,
        defaultBody: '',
        defaultIssues: '',
        defaultScope: '',
        defaultSubject: '',
    },
})
